apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mori
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: mori-hermes-config
    files:
      - config.yaml
