apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mori-tools
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: searxng-config
    files:
      - settings.yml
