"""Require Naver or Kakao social login"""

import sqlalchemy as sa
from alembic import op

revision = "0002_social_login"
down_revision = "0001_parking"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_grants",
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("code_challenge", sa.String(length=43), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("provider IN ('naver', 'kakao')", name="ck_grant_provider"),
        sa.PrimaryKeyConstraint("code_hash"),
    )
    op.create_index(
        op.f("ix_login_grants_expires_at"), "login_grants", ["expires_at"], unique=False
    )
    op.create_table(
        "oauth_flows",
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("browser_hash", sa.String(length=64), nullable=False),
        sa.Column("code_challenge", sa.String(length=43), nullable=False),
        sa.Column("client_state", sa.String(length=128), nullable=False),
        sa.Column("return_url", sa.String(length=2048), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("provider IN ('naver', 'kakao')", name="ck_oauth_provider"),
        sa.PrimaryKeyConstraint("state_hash"),
    )
    op.create_index(op.f("ix_oauth_flows_expires_at"), "oauth_flows", ["expires_at"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "social_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("provider IN ('naver', 'kakao')", name="ck_social_provider"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "subject", name="uq_social_provider_subject"),
        sa.UniqueConstraint("user_id", "provider", name="uq_social_user_provider"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["auth_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_session_id"), "refresh_tokens", ["session_id"], unique=False
    )
    op.add_column("access_tokens", sa.Column("session_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_access_tokens_session_id"), "access_tokens", ["session_id"], unique=False
    )
    op.create_foreign_key(
        "fk_access_tokens_session_id",
        "access_tokens",
        "auth_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # Existing users and parking records survive; manually issued tokens cannot bypass social login.
    op.execute("UPDATE access_tokens SET revoked_at = now() WHERE revoked_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # A rollback must not turn session-bound tokens into valid legacy tokens.
    op.execute("UPDATE access_tokens SET revoked_at = now() WHERE revoked_at IS NULL")
    op.drop_constraint("fk_access_tokens_session_id", "access_tokens", type_="foreignkey")
    op.drop_index(op.f("ix_access_tokens_session_id"), table_name="access_tokens")
    op.drop_column("access_tokens", "session_id")
    op.drop_index(op.f("ix_refresh_tokens_session_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("social_identities")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_oauth_flows_expires_at"), table_name="oauth_flows")
    op.drop_table("oauth_flows")
    op.drop_index(op.f("ix_login_grants_expires_at"), table_name="login_grants")
    op.drop_table("login_grants")
    # ### end Alembic commands ###
